### ISSUE TITLE
hi, cdn.int64ago.org 这个镜像站是没了吗？

### ISSUE THREAD

**Issue by butaixianran** [int64ago/cdnjs-extension#1]
hi, 之前一直在用 cdn.int64ago.org，非常感谢，今天上来看，发现被跳转到这里了。

请问之前的 cdn.int64ago.org 镜像站，是关闭了吗，还是改域名了？

多谢。

**Comment by int64ago** [comment]
没有关闭，只是我发现用插件的方式更优雅，而且还能使用自己的空间
之前的库依然是有效的，如果你需要搜索新的库可以按照 README.md 步骤装上插件后操作
你会发现更方便呢！
当然设置的七牛空间地址的时候，你可以使用自己的空间（需要设置镜像源），也可以继续使用我之前提供的域名：https://dn-cdnjscn.qbox.me

我已经更新了 README.md
