### ISSUE TITLE
不知道可否增加功能，连路径中/ajax/libs也替换掉

### ISSUE THREAD

**Issue by butaixianran** [int64ago/cdnjs-extension#2]
hi, 插件用了下，很感谢，确实很方便，但自建镜像就有点不划算。因此，想请问可否提供另一种链接替换方式：
连 /ajax/libs/ 也替掉。

比如，源文件：
https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-beta.0/angular2.min.js
现在是替换成：
https://自定义域名/ajax/libs/angular.js/2.0.0-beta.0/angular2.min.js
但希望能替换成：
https://自定义域名/angular.js/2.0.0-beta.0/angular2.min.js

这是因为想用cdnjs.net的空间，但想在cdnjs.com官网查找库。

cdnjs.net也是cdnjs的国内镜像，但它把路径中的/ajax/libs/给去掉了。很希望能用你的插件，连同 /ajax/libs也替掉，就可以换成它的空间，就不用自建镜像了。

**Comment by int64ago** [comment]
- 七牛实名认证的用户提供 10 G 的免费空间呢，不会不划算的
- 可以的，比如：https://o09icfrf6.qnssl.com/angular.js/2.0.0-beta.0/angular2.min.js ，但是有些地方需要注意，应你的要求，我会修改下插件，感谢建议

**Comment by butaixianran** [comment]
多谢，期待ing

**Comment by int64ago** [comment]
@butaixianran 插件已经更新了，README 也更新了，请注意阅读根据自己的需求设置
PS：https://dn-cdnjscn.qbox.me 由于我设置的镜像源的原因，不能去除 `ajax/libs/`，你新设置的空间可以自行设置的

**Comment by butaixianran** [comment]
更新了，太好用了！thanks
