### ISSUE TITLE
乱码什么鬼

### ISSUE THREAD

**Issue by SimplyY** [int64ago/cdnjs-extension#3]
![image](https://cloud.githubusercontent.com/assets/8455579/12079109/2353e2f4-b268-11e5-8455-bda56239c9fe.png)

**Comment by int64ago** [comment]
图片挂了

**Comment by int64ago** [comment]
图片看到了……应该是我没制定编码……这就改

**Comment by SimplyY** [comment]
恢复速度好快=。=，辛苦了

**Comment by int64ago** [comment]
@SimplyY , Hi Chrome Web Store 已经更新到 1.1.1 了，你更新后试试呢

其实我改+打包上传只用了 1min，Google 发布流程就走了十几分钟……

**Comment by int64ago** [comment]
PS：你的地址貌似少了  `http://`

**Comment by SimplyY** [comment]
666
